/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package buyer;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int BestCostEditText=0x7f050006;
        public static final int BestCostTextView=0x7f050005;
        public static final int BookEditText=0x7f050003;
        public static final int BookTextView=0x7f050002;
        public static final int BuyButton=0x7f050010;
        public static final int DeadlineEditText=0x7f05000b;
        public static final int DeadlineTextView=0x7f05000a;
        public static final int ExitButton=0x7f050011;
        public static final int ListViewCaption=0x7f05000d;
        public static final int MaxCostTextView=0x7f050007;
        public static final int MazCostEditText=0x7f050008;
        public static final int MessageListView=0x7f05000e;
        public static final int ResetButton=0x7f050012;
        public static final int SetButton=0x7f05000c;
        public static final int widget55=0x7f050000;
        public static final int widget72=0x7f050001;
        public static final int widget81=0x7f050004;
        public static final int widget87=0x7f050009;
        public static final int widget94=0x7f05000f;
    }
    public static final class layout {
        public static final int android_buyer_gui=0x7f030000;
    }
    public static final class string {
        public static final int agent_msisdn=0x7f040003;
        public static final int app_name=0x7f040000;
        public static final int jade_platform_address=0x7f040001;
        public static final int jade_platform_port=0x7f040002;
    }
}
