/* Generated By:JavaCC: Do not edit this line. SLParserConstants.java */
package jade.semantics.lang.sl.parser;

public interface SLParserConstants {

  int EOF = 0;
  int AOP = 6;
  int OPEN_BRACKET = 7;
  int CLOSE_BRACKET = 8;
  int PIPEKW = 9;
  int EQUALSKW = 10;
  int SEMICOLONKW = 11;
  int METAPIPEKW = 12;
  int METAOPTIONKW = 13;
  int BELIEVEKW = 14;
  int UNCERTAINTYKW = 15;
  int INTENTIONKW = 16;
  int PERSISTENTGOALKW = 17;
  int ORKW = 18;
  int ANDKW = 19;
  int NOTKW = 20;
  int SETKW = 21;
  int ALLKW = 22;
  int ANYKW = 23;
  int IOTAKW = 24;
  int SOMEKW = 25;
  int DONEKW = 26;
  int TRUEKW = 27;
  int EQUIVKW = 28;
  int FALSEKW = 29;
  int ACTIONKW = 30;
  int RESULTKW = 31;
  int EXISTSKW = 32;
  int FORALLKW = 33;
  int IMPLIESKW = 34;
  int FEASIBLEKW = 35;
  int SEQUENCEKW = 36;
  int PARAMETER_NAME = 37;
  int VARIABLE = 38;
  int META_VARIABLE = 39;
  int INTEGER = 40;
  int SIGN = 41;
  int HEX_LITERAL = 42;
  int FLOAT = 43;
  int MANTISSA = 44;
  int EXPONENT = 45;
  int DATE_TIME = 46;
  int YEAR = 47;
  int MONTH = 48;
  int DAY = 49;
  int HOUR = 50;
  int MINUTE = 51;
  int SECOND = 52;
  int MILLISECOND = 53;
  int TYPE_DESIGNATOR = 54;
  int STRING_LITERAL = 55;
  int WORD = 56;
  int BYTES = 57;
  int DEC_LITERAL = 58;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<AOP>",
    "<OPEN_BRACKET>",
    "<CLOSE_BRACKET>",
    "<PIPEKW>",
    "<EQUALSKW>",
    "<SEMICOLONKW>",
    "<METAPIPEKW>",
    "<METAOPTIONKW>",
    "<BELIEVEKW>",
    "<UNCERTAINTYKW>",
    "<INTENTIONKW>",
    "<PERSISTENTGOALKW>",
    "<ORKW>",
    "<ANDKW>",
    "<NOTKW>",
    "<SETKW>",
    "<ALLKW>",
    "<ANYKW>",
    "<IOTAKW>",
    "<SOMEKW>",
    "<DONEKW>",
    "\"true\"",
    "<EQUIVKW>",
    "\"false\"",
    "<ACTIONKW>",
    "<RESULTKW>",
    "<EXISTSKW>",
    "<FORALLKW>",
    "<IMPLIESKW>",
    "<FEASIBLEKW>",
    "<SEQUENCEKW>",
    "<PARAMETER_NAME>",
    "<VARIABLE>",
    "<META_VARIABLE>",
    "<INTEGER>",
    "<SIGN>",
    "<HEX_LITERAL>",
    "<FLOAT>",
    "<MANTISSA>",
    "<EXPONENT>",
    "<DATE_TIME>",
    "<YEAR>",
    "<MONTH>",
    "<DAY>",
    "<HOUR>",
    "<MINUTE>",
    "<SECOND>",
    "<MILLISECOND>",
    "<TYPE_DESIGNATOR>",
    "<STRING_LITERAL>",
    "<WORD>",
    "<BYTES>",
    "<DEC_LITERAL>",
  };

}
