/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package jade.android;

public final class R {
    public static final class array {
        public static final int comActList=0x7f040000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int backBtn=0x7f06000b;
        public static final int commAct=0x7f060006;
        public static final int content=0x7f06000d;
        public static final int messageList=0x7f06000a;
        public static final int receiver=0x7f060004;
        public static final int replyBtn=0x7f060008;
        public static final int sendBtn=0x7f060007;
        public static final int sender=0x7f060002;
        public static final int widget0=0x7f060000;
        public static final int widget26=0x7f060001;
        public static final int widget28=0x7f060003;
        public static final int widget30=0x7f060005;
        public static final int widget41=0x7f060009;
        public static final int widget45=0x7f06000c;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int send_message=0x7f030001;
    }
    public static final class string {
        public static final int activity_local_jade_controller=0x7f050000;
        public static final int app_name=0x7f050001;
        public static final int app_name2=0x7f050002;
        public static final int bind_service=0x7f050007;
        public static final int close=0x7f05001c;
        public static final int confirm=0x7f05001b;
        public static final int container_key=0x7f050015;
        public static final int content=0x7f05001a;
        public static final int hello_jade=0x7f050012;
        public static final int host_key=0x7f050013;
        public static final int local_jade_binding=0x7f050003;
        public static final int local_jade_controller=0x7f050004;
        public static final int local_service_connected=0x7f05000c;
        public static final int local_service_disconnected=0x7f05000d;
        public static final int local_service_failure=0x7f050010;
        public static final int local_service_label=0x7f050011;
        public static final int local_service_started=0x7f05000e;
        public static final int local_service_stopped=0x7f05000f;
        public static final int menu_jade_controller=0x7f050016;
        public static final int menu_send_message=0x7f050017;
        public static final int menu_test_puto2aobject=0x7f050018;
        public static final int message_received=0x7f05001d;
        public static final int port_key=0x7f050014;
        public static final int receiver=0x7f050019;
        public static final int send_command=0x7f05000a;
        public static final int send_message=0x7f050009;
        public static final int start_service=0x7f050005;
        public static final int stop_service=0x7f050006;
        public static final int test_puto2aobject=0x7f05000b;
        public static final int unbind_service=0x7f050008;
    }
}
