/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package jade.android;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int bind=0x7f050000;
        public static final int sendCommand=0x7f050002;
        public static final int unbind=0x7f050001;
    }
    public static final class layout {
        public static final int jade_bind_activity=0x7f030000;
        public static final int main=0x7f030001;
        public static final int send_command=0x7f030002;
    }
    public static final class string {
        public static final int activity_local_jade_controller=0x7f040000;
        public static final int app_name=0x7f040001;
        public static final int app_name2=0x7f040002;
        public static final int bind_service=0x7f040007;
        public static final int close=0x7f04001d;
        public static final int confirm=0x7f04001c;
        public static final int container_key=0x7f040015;
        public static final int content=0x7f04001b;
        public static final int hello_jade=0x7f040012;
        public static final int host_key=0x7f040013;
        public static final int local_jade_binding=0x7f040003;
        public static final int local_jade_controller=0x7f040004;
        public static final int local_service_connected=0x7f04000c;
        public static final int local_service_disconnected=0x7f04000d;
        public static final int local_service_failure=0x7f040010;
        public static final int local_service_label=0x7f040011;
        public static final int local_service_started=0x7f04000e;
        public static final int local_service_stopped=0x7f04000f;
        public static final int menu_jade_controller=0x7f040017;
        public static final int menu_send_message=0x7f040018;
        public static final int menu_test_puto2aobject=0x7f040019;
        public static final int msg_received=0x7f040016;
        public static final int port_key=0x7f040014;
        public static final int receiver=0x7f04001a;
        public static final int send_command=0x7f04000a;
        public static final int send_message=0x7f040009;
        public static final int start_service=0x7f040005;
        public static final int stop_service=0x7f040006;
        public static final int test_puto2aobject=0x7f04000b;
        public static final int unbind_service=0x7f040008;
    }
}
