// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package FIPA;

//
// IDL:FIPA/MTS:1.0
//
/***/

public interface MTSOperations
{
    //
    // IDL:FIPA/MTS/message:1.0
    //
    /***/

    public void
    message(FipaMessage aFipaMessage);
}
